baseURL = "https://blog.usarr.tech"
languageCode = "es-ES"
title = "Blog | Usarral"

disableHugoGeneratorInject = true
defaultContentLanguage = "es"
preserveTaxonomyNames = true
paginate = 7

[permalinks]
  posts = "/:filename/"

[params]
  description = "Blog | Usarral"
  image = "/favicon/apple-touch-icon.png"

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats]
  [outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true


